import { createFileRoute, Link } from "@tanstack/react-router";
import {
  ArrowLeft, FileText, Download, Share2, PawPrint, CheckCircle2,
  AlertCircle, Sparkles, Weight, Moon, Droplets, Syringe,
} from "lucide-react";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PhoneShell } from "@/components/PhoneShell";
import { useAuth } from "@/lib/auth";
import { computeDigitalTwin } from "@/lib/digitalTwin";
import { downloadHealthReport, getHealthReportBlob } from "@/lib/reportGenerator";
import { pageVariants, childVariants, cardVariants, staggerContainer, tapScale } from "@/lib/motion";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports — CatTwin AI" }] }),
  component: Reports,
});

function Reports() {
  const { user } = useAuth();
  const cats = user?.cats ?? [];
  const activeCat = cats[0] ?? null;
  const catId = activeCat?.id ?? "";

  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [shareError, setShareError] = useState("");

  const weightLogs = (user?.weightLogs ?? []).filter((l) => l.catId === catId);
  const sleepLogs = (user?.sleepLogs ?? []).filter((l) => l.catId === catId);
  const hydrationLogs = (user?.hydrationLogs ?? []).filter((h) => h.catId === catId);
  const meals = (user?.meals ?? []).filter((m) => m.catId === catId);
  const vetRecords = (user?.vetRecords ?? []).filter((r) => r.catId === catId);
  const hasEnoughData = weightLogs.length > 0 || sleepLogs.length > 0 || meals.length > 0;
  const twin = computeDigitalTwin(user, catId);

  const includedSections = [
    { icon: Sparkles, label: "AI Health Summary", ok: twin.hasAnyData },
    { icon: Weight, label: "Weight History", ok: weightLogs.length > 0, count: weightLogs.length },
    { icon: Moon, label: "Sleep & Activity", ok: sleepLogs.length > 0, count: sleepLogs.length },
    { icon: Droplets, label: "Hydration Log", ok: hydrationLogs.length > 0, count: hydrationLogs.length },
    { icon: Syringe, label: "Vaccination & Medical", ok: vetRecords.length > 0, count: vetRecords.length },
  ];

  async function handleDownload() {
    setDownloading(true);
    await new Promise((r) => setTimeout(r, 500));
    const ok = downloadHealthReport(user, activeCat);
    setDownloading(false);
    if (ok) {
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    }
  }

  async function handleShare() {
    setShareError("");
    setSharing(true);
    try {
      const blob = getHealthReportBlob(user, activeCat);
      if (!blob || !activeCat) throw new Error("no-data");
      const filename = `CatTwin-Health-Report-${activeCat.name.replace(/\s+/g, "-")}.pdf`;
      const file = new File([blob], filename, { type: "application/pdf" });
      if (typeof navigator !== "undefined" && navigator.canShare?.({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `${activeCat.name}'s CatTwin Health Report`,
          text: "Health report generated by CatTwin AI — share with your veterinarian.",
        });
      } else {
        // Fallback: browsers without file-sharing support just download instead.
        downloadHealthReport(user, activeCat);
      }
    } catch (err) {
      if ((err as Error)?.name !== "AbortError") {
        setShareError("Couldn't share the report on this device. Try downloading it instead.");
      }
    } finally {
      setSharing(false);
    }
  }

  if (!activeCat) {
    return (
      <PhoneShell>
        <div className="px-6 pt-12 pb-4 flex items-center gap-3">
          <Link to="/" className="w-9 h-9 rounded-full bg-secondary flex items-center justify-center"><ArrowLeft size={18} /></Link>
          <h1 className="font-serif text-xl font-semibold flex-1 text-center pr-9">Reports</h1>
        </div>
        <div className="px-6 py-16 flex flex-col items-center text-center">
          <div className="w-20 h-20 rounded-full bg-[var(--coral-soft)] flex items-center justify-center mb-5"><PawPrint size={40} style={{ color: "var(--coral)" }} /></div>
          <h2 className="font-serif text-xl font-semibold mb-2">No cat added yet</h2>
          <p className="text-sm text-muted-foreground mb-6 max-w-[240px]">Add a cat to generate a health report.</p>
          <Link to="/" className="bg-[var(--nav-dark)] text-white text-sm font-medium rounded-2xl px-5 py-3 hover:bg-[var(--coral)] transition-colors">Go to Home</Link>
        </div>
      </PhoneShell>
    );
  }

  return (
    <PhoneShell>
      <motion.div variants={pageVariants} initial="hidden" animate="visible" exit="exit">
        <motion.div variants={childVariants} className="px-6 pt-12 pb-4 flex items-center gap-3">
          <motion.div whileTap={tapScale}>
            <Link to="/" className="w-9 h-9 rounded-full bg-secondary flex items-center justify-center"><ArrowLeft size={18} /></Link>
          </motion.div>
          <h1 className="font-serif text-xl font-semibold flex-1 text-center pr-9">Reports</h1>
        </motion.div>

        <motion.div variants={staggerContainer} initial="hidden" animate="visible" className="px-6 space-y-5 pb-6">
          {/* Preview card */}
          <motion.div variants={cardVariants} className="bg-card rounded-3xl p-5 shadow-[0_4px_16px_-8px_rgba(0,0,0,0.1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-2xl bg-[var(--coral-soft)] flex items-center justify-center shrink-0">
                <FileText size={22} style={{ color: "var(--coral)" }} />
              </div>
              <div>
                <h2 className="font-serif text-lg font-semibold leading-tight">{activeCat.name}'s Health Report</h2>
                <p className="text-xs text-muted-foreground mt-0.5">Generated from logged data · updated live</p>
              </div>
            </div>

            {!hasEnoughData ? (
              <p className="text-sm text-muted-foreground text-center py-4">Log some weight, sleep, or feeding data to generate a meaningful report.</p>
            ) : (
              <div className="flex items-center gap-4 mb-2">
                <div className="text-center">
                  <p className="font-serif text-3xl font-semibold" style={{ color: "var(--coral)" }}>{twin.overallScore}</p>
                  <p className="text-[11px] text-muted-foreground mt-0.5">Health Score</p>
                </div>
                <div className="flex-1 text-sm text-muted-foreground leading-relaxed">
                  {twin.summary}
                </div>
              </div>
            )}
          </motion.div>

          {/* Included sections */}
          <motion.div variants={cardVariants} className="bg-card rounded-3xl p-5 shadow-[0_4px_16px_-8px_rgba(0,0,0,0.1)]">
            <h2 className="font-serif text-lg font-semibold mb-3">Included in this report</h2>
            <div className="space-y-2">
              {includedSections.map((s) => (
                <div key={s.label} className="flex items-center gap-3 py-1.5">
                  <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 ${s.ok ? "bg-[var(--coral-soft)]" : "bg-secondary"}`}>
                    <s.icon size={14} style={s.ok ? { color: "var(--coral)" } : undefined} className={!s.ok ? "text-muted-foreground" : undefined} />
                  </div>
                  <span className={`flex-1 text-sm ${s.ok ? "text-foreground" : "text-muted-foreground"}`}>{s.label}</span>
                  {s.ok ? (
                    <span className="flex items-center gap-1 text-xs text-emerald-600 dark:text-emerald-400">
                      <CheckCircle2 size={12} /> {s.count !== undefined ? `${s.count} entries` : "Included"}
                    </span>
                  ) : (
                    <span className="text-xs text-muted-foreground">No data</span>
                  )}
                </div>
              ))}
            </div>
          </motion.div>

          {/* Actions */}
          <motion.div variants={childVariants} className="space-y-3">
            <motion.button
              onClick={handleDownload}
              disabled={!hasEnoughData || downloading}
              whileHover={hasEnoughData ? { scale: 1.01 } : {}}
              whileTap={hasEnoughData ? tapScale : {}}
              className={`w-full flex items-center justify-center gap-2 rounded-2xl py-3.5 text-sm font-medium transition-colors ${
                hasEnoughData ? "bg-[var(--nav-dark)] hover:bg-[var(--coral)] text-white" : "bg-[var(--nav-dark)] text-white/40 cursor-not-allowed"
              }`}
            >
              <AnimatePresence mode="wait" initial={false}>
                {downloading ? (
                  <motion.span key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2">
                    <span className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin" /> Preparing PDF…
                  </motion.span>
                ) : downloaded ? (
                  <motion.span key="done" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2">
                    <CheckCircle2 size={16} /> Downloaded!
                  </motion.span>
                ) : (
                  <motion.span key="idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2">
                    <Download size={16} /> Download PDF Report
                  </motion.span>
                )}
              </AnimatePresence>
            </motion.button>

            <motion.button
              onClick={handleShare}
              disabled={!hasEnoughData || sharing}
              whileHover={hasEnoughData ? { scale: 1.01 } : {}}
              whileTap={hasEnoughData ? tapScale : {}}
              className={`w-full flex items-center justify-center gap-2 rounded-2xl py-3.5 text-sm font-medium transition-colors border ${
                hasEnoughData ? "border-border bg-card hover:bg-secondary text-foreground" : "border-border bg-card text-muted-foreground cursor-not-allowed"
              }`}
            >
              {sharing ? (
                <span className="w-4 h-4 rounded-full border-2 border-current/30 border-t-current animate-spin" />
              ) : (
                <Share2 size={16} />
              )}
              Share with Veterinarian
            </motion.button>

            <AnimatePresence>
              {shareError && (
                <motion.div initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                  className="flex items-center gap-2 bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-300 rounded-xl px-4 py-3 text-xs">
                  <AlertCircle size={14} className="shrink-0" /> {shareError}
                </motion.div>
              )}
            </AnimatePresence>

            {!hasEnoughData && (
              <p className="text-center text-xs text-muted-foreground">Available once you've logged some health data.</p>
            )}
          </motion.div>
        </motion.div>
      </motion.div>
    </PhoneShell>
  );
}
